import type { Metadata } from "next";
import Providers from './providers';
// import "./globals.css";
import "@/shared/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
