import type { Metadata } from "next";
import Providers from "./providers";
import "@/shared/styles/index.css";
import Header from "@/shared/ui/header/header";

export const metadata: Metadata = {
  title: "Create Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[1440px] mx-auto">
          <Header />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
